### PR TITLE
SiN PCM + cdc pcell: update docs directory

### PR DESCRIPTION
**Pull request by mustafacc**

### CODE REVIEW

**Comment by mustafacc** [comment]
Added SiN PCM layout

**Comment by lukasc-ubc** [comment]
Can you move the structures onto the SiN layer?  
Note that ANT requested we switch to Layer 4/0.  
I have made the change to the .lyt file

**Comment by mustafacc** [comment]
Changed to 4/0 and updated the PCM with O-band test structures as well
- Bragg gratings DOE updated to the appropriate range  after measurements
- increased MZIs DL
- O-band PCM

**Comment by lukasc-ubc** [comment]
Hi @mustafacc they show up on 1/0 instead of 4/0, for some reason.

**Pull request merged**
