### PR TITLE
Added 895 GC and YBranch model

### PR DESCRIPTION
**Pull request by m2wentla**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
YBranch wasn't working; things weren't connected.
Fixing.
image

**Comment by lukasc-ubc** [comment]
image
looks like the splitters have the same ratio.

**Comment by lukasc-ubc** [comment]
Problem with the terminator.

image

**Comment by lukasc-ubc** [comment]
How did you simulate the loss for the Bezier parameters?  The loss numbers were much higher than 0.01 dB in the mode calculations.

**Comment by m2wentla** [comment]
I used the loss_vs_bezier FDTD simulation that was included with the SiEPIC Passives course resources. I'm also not entirely convinced by the results I found. I realized last night that I probably placed the monitors asymmetrically which would affect the loss that was calculated.

**Comment by JackdeGooyer** [comment]
I could not tell you where the oscillations are from. We think it is from the placement of the mode expansion solver for S-param extraction. They should not have the same ratio, I will look into that, but it may come from the previous concern. I used the Y-branch S-param extractor and modified for four ports. 

We did not factor in fabrication bias.

**Pull request merged**
