### PR TITLE
Add Optimal Routing Tapers for TE1550nm Devices

### PR DESCRIPTION
**Pull request by seanlam97**
Two routing tapers that taper from 0.5um width to 3um width are added:
1. 20um length taper gives the shortest taper that matches the length and loss in a 0.5um width waveguide (assuming 3dB/cm loss). Loss of taper is ~5mdB/device.
2. 40um length taper gives the minimum loss for taper length. Shorter yields more modal loss; longer yields more propagation loss. Loss of taper is ~2mdB/device.

### CODE REVIEW

**Comment by seanlam97** [comment]
Workflow errors are coming from ebeam_test_bends in the EBeam-Beta library and codecov. Please check.

**Comment by lukasc-ubc** [comment]
Hi Sean,

Thank you for the PR.

The codecov error is as follows:
> [2024-05-08T21:34:01.081Z] ['error'] There was an error running the uploader: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: 429 - {'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 3174s.', code='throttled')}


It should be working again in ~1 hour?

There are two actions for the PDK tests: a) Docker container, b) PyPi.

a)

The Docker one failed, with the following:
> ERROR: /root/.klayout/salt/SiEPIC-Tools/klayout_dot_config/tech/GSiP/pymacros/GSiP Library.lym:113: RuntimeError: Unable to open file: /root/.klayout/salt/SiEPIC-Tools/klayout_dot_config/tech/GSiP/gds/building_blocks//edge_coupler_1550.gds (errno=2) in Layout.read


And 
> Caught PCellRegistrationError: Pcell ebeam_test_bends could not be registered in library EBeam_Beta


I ran the same command as in the Docker on my computer, and it doesn’t produce the same error.

> ***@***.*** siepic_ebeam_pdk % /Applications/klayout-0.28.17-macOS-Sonoma-1-qt5Brew-RsysPhb311.app/Contents/MacOS/klayout -zz -r pymacros/EBeam_Lib_PCellTests.py


And I get a clean check:
>   * Testing cell: ebeam_test_bends
> Number of bends: 202
> done layout_waveguide3 test_bends
>   * Testing cell: ebeam_dc_halfring_arc

I also checked it using the older version 0.28.13, and also fine.

b) the PyPi test is working (except for CodeCov).

Any idea how to debug the Docker fail?

thanks

**Comment by lukasc-ubc** [comment]
Strange. No error after merging.  

￼

**Comment by seanlam97** [comment]
Typically to debug these workflow errors, we would need to run an instance of the container and manually run the commands from the workflow (within our servers). Regardless, glad that this is working.

**Pull request merged**
