### PR TITLE
Update phase shifter and small bug fix

### PR DESCRIPTION
**Pull request by Guowu-Mcgill**
contact via & N++ layers of folded design expanded and moved away from the waveguide, based on ANT rules, and similar to the non-folded design.

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
more fixes from my side.. the waveguide thing
image
and also updating SiEPIC-Tools

**Comment by lukasc-ubc** [comment]
@Guowu-Mcgill 

I was thinking - what if we extended the slab to cover the U-turns?  This way, the heat would spread out more and heat the waveguides there too.  Or would that be less efficient since the U-turn area is quite large?

Could you take a look at the tapers?  they aren't quite the same everywhere.

**Comment by Guowu-Mcgill** [comment]
Hi professor Lukas,

I did a very simple simulation using Lumerical device. Try to mimic the situation where the heat is apply at around -5 – - 2 and 2- 5 um. As we can see from screenshot below, the temperature increase will transferred to the place 5 – 10 um away. However, the U shape is too far to the heat source. I guess, even we extend the slab, it will not have a large impact to energy efficiency! Also, if we extend to U shape place, we may need large bend radius.

For the taper, you are referring the input and output taper is not the same as the rest? I can fix it to make all of them same. Using a wider end taper, I hope the loss for transferring for strip to slab waveguide mode will be reduced.

[cid:image001.png@01D62C59.62167A00]

Regards,

Guowu Zhang
PhD candidate, Photonic Data Comm. Team
Department of Electronic Engineering, McGill University
3480 Rue University, Montreal H3A 0E9, QC, Canada

**Comment by lukasc-ubc** [comment]
I can't see your picture...  can you try dragging it into the GitHub window (follow the link in the email).

**Comment by Guowu-Mcgill** [comment]
sdsd
Can you see it now?

**Comment by lukasc-ubc** [comment]
Regarding the taper, the field doesn't extend too far, probably only about 1-2 µm away from the waveguide.  So we don't need to make the taper too wide.  On the other hand, if you make it wider, it gives it a steeper transition which will introduce loss as it won't be adiabatic anymore.  So there is an optimal shape...

As for your point about the heat spreading, that is a good point.  How far up/down does the heat spread?  i.e., what is the larger number of folds that we should consider?  Only about 5-10 µm?

So 7 folds is too many?
image

**Comment by lukasc-ubc** [comment]
Given the limited spreading, what we if we put the two electrodes (and large contacts) on the outside of the structure, and had 7 waveguides in between in the middle?  Seems like the contact via are the limiting factor.

Or, instead of having 6 contact via inside the device, we could have 2, and put them both outside the device (since a waveguide u-turn).  But the resistance would be increased by 5X, to 700 ohm.

**Comment by Guowu-Mcgill** [comment]
heater_effi

From simulation, the heater usually spread to 5 - 10 um away. Or, we may draw another Npp strip close to top and bottom.

**Comment by Guowu-Mcgill** [comment]
taper_image
Regarding the taper, what about this? i change the code so that they have the same shape.

**Comment by lukasc-ubc** [comment]
Rather than having 4 heaters - what if we move the heaters above/below, and have all the waveguides inside. If we go down this route, let's leave the current xxx_folded device, copy and paste it into a new one (so we don't break the old one).

What we have done already will be useful for processes where the VC is reduced in size (say 1 µm or smaller)

Tapers above - yes, looks good.

**Comment by Guowu-Mcgill** [comment]
Make sense, i will copy what we have now and generate new one as we discussed!

**Comment by Guowu-Mcgill** [comment]
draft_new_version
Hi Professor Lukas,

Could you please check if this is something you were refering? I could send you the code.

**Comment by Guowu-Mcgill** [comment]
with_9_wg

We could also reduce the gap between two adjacent waveguide to 1 um since from simulation andreference, the crosstalk is low enough.

**Comment by lukasc-ubc** [comment]
That looks great!
We can also put in the slab cutouts like I did for the non-folded design.  
1 micron sounds good (there is a crosstalk figure in my book). But for asymmetric waveguides we may be able to get even closer.

**Comment by Guowu-Mcgill** [comment]
final
Hi Professor Lukas,
Yes, i use the code from your book to do the simulation. The only concern is if the input/output taper width is wider enough. 

Please see the screenshot for the final version. I also add an oxide open surround the NPP so that we could prevent the heater from spreading to unwanted regions (as in the reference paper). i am uploading it to github.

**Comment by lukasc-ubc** [comment]
Interesting idea to add the oxide open / deep trench.  We probably won’t have that in the run next week, but good to keep in mind for future runs.  That trench idea works really well if it includes an undercut step, which ANT has done for our JSTQE paper, so it is possible.

We need to be careful for the input/output waveguides.  Probably switching them to strip I/O would fix the current issue.

**Comment by Guowu-Mcgill** [comment]
Hi Professor Lukas,

I update the phase shifter. You may check from your side. I just copy and paste from local .py file. But it do not include symbols like "< >". I hope it will work.

oxide open is an optional choice. if user need it, they can just select the option. Otherwise, it will not show up by default.

Regarding the taper, i will do some simulation for the taper to investigate the loss.

**Pull request merged**
